services:
  mihomo:
    image: mihomo:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mihomo
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      mihomovlan: # macvlan name
        ipv4_address: 192.168.2.2 # container (gateway) ip address
    environment:
      QUIC: "false" # allow quic (udp 443)
      CONTAINER_PROXY: "false" # forward the container's own traffic to tproxy
      BYPASS_CN: "false" # bypass cn ip to mihomo kernel (valid only in redir-host mode; fake-ip mode requires DNS routing)
    volumes:
      - './config.yaml:/mihomo/config/config.yaml'
      - './cn_cidr.txt:/mihomo/config/cn_cidr.txt'

networks:
  mihomovlan:
    name: mihomovlan
    driver: macvlan
    driver_opts:
      parent: eth0 # modify it to match your network interface name
    ipam:
      config: # modify the following content to match your network env
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.64/26"
          gateway: "192.168.2.1"

# if you already have a macvlan
# networks:
#   yourvlan:
#     external: true
